# MySQL properties
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useTimezone=true&serverTimezone=UTC
    username: 'luccas'
    password: '061294'
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

# Spring Boot Server properties
server:  
  port: 9000